[package]
name = "bless"
version = "0.0.1"
edition = "2021"

[dependencies]
flate2 = "1.0"
uuid = { version = "1", features = ["v4"] }
clap = "3.0"
wild = "2.2.1"
duct = "0.13.7"
tokio = {"version"="1.36.0", features=["rt-multi-thread", "macros"]}
async-trait = "0.1.77"
