from_latest_tag = false
ignore_merge_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []
tag_prefix = "v"

[git_hooks]

[commit_types]
enh = { changelog_title = "Enhancements" }
bug = { changelog_title = "Bugfixes" }
maint = { changelog_title = "Maintenance" }
prj = { changelog_title = "Project" }
doc = { changelog_title = "Documentation" }
tst = { changelog_title = "Tests" }
bld = { changelog_title = "Buildsystem" }
gen = { changelog_title = "Generated" }
dat = { changelog_title = "Data" }
bench = { changelog_title = "Benchmarks" }

[changelog]
path = "CHANGELOG.md"
authors = [
        { username = "HaoZeke", signature = "Rohit Goswami" }
]

[bump_profiles]

[packages]
